import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Birlik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center text-sky-400 font-mono">
        <h1 className="text-6xl font-bold mb-4">Welcome to Birlik</h1>
        <h2 className="text-2xl font-semibold w-1/2 mb-4">
          Purpose of this project is to combine all requirement related
          documentation in a central point so that it is easier to relate to or
          update requirements and artifacts created around the requirements
        </h2>
        <h2 className="text-xl font-medium w-1/2">
          My approach is to combine BR, FR, User Story, test scenarios , qa/dev
          notes etc. in all one page and allow user to show only what the user
          needs (filter out all other info). Also allow user to import filtered
          version so it can be easily used in other documents (like business
          requirements document, functional requirement document, test strategy
          etc.)
        </h2>
        <Link href="./birlik">
          <a className="mt-4 hover:text-sky-300 w-1/2 hover:text-xl">
            You can display prototype by clicking here.Keep in mind that this is
            only a prototype. There are many features that could be added to
            help eliminating errors and make documentation process smooth.
          </a>
        </Link>
      </div>
    </>
  );
};

export default Home;
